### ISSUE TITLE
Unable to deal damage to monster after a certain number of rounds

### ISSUE THREAD

**Issue by theshark** [The-Sous-Chefs/Cooking-Card-Game#28]
Current Behavior: Basic Attack no longer lowers HP of enemy.

This video shows how Basic Attack does not lower enemy's hp but Restore Mana does still work.

https://user-images.githubusercontent.com/273658/117548981-83567480-affd-11eb-88b7-1c3b6b6aa53f.mp4

**Comment by Ian-Thorne** [comment]
I think this is because of the addition of multiple enemies. Since the basic attack doesn't have an interface for selecting a target, it always attacks the enemy with an ID of 0, but if that enemy has been defeated then it won't do anything. We could either fix this by 1) having the basic attack deal less damage to all enemies or 2) having the basic attack always attack the left-most or lowest-HP enemy.

**Comment by Ian-Thorne** [comment]
We changed the basic attack to deal 2 damage to all enemies, rather than 3 to a single one, since it didn't have an interface for providing a target and always attacking the left-most enemy felt a bit like a hack.
